version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    container_name: macpaw_data-eng
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${LOCAL_PG_USER}
      - POSTGRES_PASSWORD=${LOCAL_PG_PASSWORD}
      - POSTGRES_DB=${LOCAL_PG_DB}
volumes:
  postgres_data:
  static_volume: